const modules = [
  { id: 'comprehension', index: '01', title: 'Comprehension', description: 'Distinguer l’information, l’idée et la position d’un auteur.', icon: 'book-open', questions: [
    q('Texte court', 'Une mairie transforme trois voies de circulation en pistes cyclables. Dans son bilan, elle note que les commerces voisins ont vu leur frequentation augmenter le week-end, sans pouvoir etablir a elle seule un lien de cause a effet. Quelle conclusion est la plus rigoureuse ?', ['La transformation a necessairement accru les ventes.', 'Les pistes cyclables ont fait diminuer la circulation.', 'Une hausse de frequentation est constatee, mais sa cause reste indeterminee.', 'Les commerces ne beneficiaient pas auparavant de visiteurs le week-end.', 'La mairie aurait du supprimer toutes les voies de circulation.'], 2, 'Le texte constate une hausse mais refuse d’en attribuer la cause avec certitude.'),
    q('Texte court', 'La publication de donnees ouvertes ne garantit pas leur appropriation par les citoyens. Encore faut-il que ces donnees soient lisibles, mises en contexte et accessibles aux personnes qui souhaitent les utiliser. Quelle idee resume le mieux le passage ?', ['Les donnees ouvertes sont inutiles.', 'La transparence depend aussi de la qualite de presentation des donnees.', 'Les citoyens refusent les outils numeriques.', 'Les donnees doivent rester reservees aux experts.', 'La mise en contexte supprime tout risque d’erreur.'], 1, 'L’auteur nuance : publier ne suffit pas, il faut rendre les informations utilisables.'),
    q('Inference', 'Un observateur ecrit : « Les villes qui plantent des arbres n’echappent pas aux canicules ; elles se donnent simplement davantage de moyens d’en limiter les effets. » Quelle affirmation est compatible avec cette phrase ?', ['Les arbres empechent toute hausse de temperature.', 'Planter des arbres est inutile face aux canicules.', 'Les arbres constituent une reponse partielle a un probleme plus vaste.', 'Les canicules ne concernent que les villes sans arbres.', 'La plantation doit remplacer toutes les autres politiques publiques.'], 2, 'Le mot « simplement » indique une action utile, mais non suffisante.'),
    q('Titre', 'Un article decrit comment des bibliotheques pretent des outils de bricolage, des graines et parfois des instruments de musique. Il insiste sur la mise en commun des ressources plutot que sur l’accumulation individuelle. Quel titre convient le mieux ?', ['La disparition des bibliotheques', 'Acheter moins, partager davantage', 'Les outils de bricolage les plus performants', 'Le silence dans les lieux publics', 'La fin de la lecture papier'], 1, 'Le sujet central est le partage des ressources propose par ces bibliotheques.'),
    q('Nuance', '« Le teletravail a rendu certains echanges plus rapides, mais il a aussi prive les equipes de conversations informelles utiles a la circulation de certaines informations. » Quelle proposition respecte la nuance ?', ['Le teletravail ralentit tous les echanges.', 'Les echanges informels sont inutiles.', 'Le teletravail produit a la fois des gains et des pertes.', 'Le teletravail doit etre interdit.', 'Les equipes communiquent uniquement de facon informelle.'], 2, 'La phrase met explicitement en regard un avantage et une limite.') ] },
  { id: 'calcul', index: '02', title: 'Calcul', description: 'Resoudre vite, sans calculatrice, les problemes utiles.', icon: 'calculator', questions: [
    q('Pourcentage', 'Un abonnement coute 80 euros. Son prix augmente de 15 %, puis beneficie d’une remise de 15 %. Quel est son prix final ?', ['80 euros', '78,20 euros', '82 euros', '68 euros', '92 euros'], 1, '80 x 1,15 x 0,85 = 78,20. Une hausse puis une baisse de meme pourcentage ne s’annulent pas.'),
    q('Vitesse', 'Un train parcourt 180 km en 2 h 15 min. Quelle est sa vitesse moyenne ?', ['70 km/h', '75 km/h', '80 km/h', '85 km/h', '90 km/h'], 2, '2 h 15 min = 2,25 h. Donc 180 / 2,25 = 80 km/h.'),
    q('Proportion', 'Dans une promotion de 120 etudiants, 35 % suivent un cours d’allemand. Combien n’en suivent pas ?', ['35', '42', '78', '80', '85'], 2, '35 % de 120 = 42. Il reste donc 120 - 42 = 78 etudiants.'),
    q('Algebre', 'Si 3x - 5 = 19, quelle est la valeur de x ?', ['6', '7', '8', '9', '24'], 2, '3x = 24 puis x = 8.'),
    q('Moyenne', 'La moyenne de quatre notes est 13. Trois notes sont 10, 14 et 16. Quelle est la quatrieme note ?', ['10', '11', '12', '13', '14'], 2, 'Le total est 4 x 13 = 52. Les trois notes totalisent 40, il manque 12.') ] },
  { id: 'argumentation', index: '03', title: 'Raisonnement', description: 'Identifier la consequence, la cause et le bon argument.', icon: 'messages-square', questions: [
    q('Argument', '« Le campus devrait ouvrir la bibliotheque le dimanche, car de nombreux etudiants travaillent en semaine. » Quel fait renforce le plus cet argument ?', ['Les etudiants aiment lire des romans.', 'La bibliotheque est deja ouverte le lundi.', 'Les salles de travail sont presque pleines le samedi apres-midi.', 'Le campus est situe pres d’une gare.', 'Les livres numeriques existent.'], 2, 'Une forte affluence juste avant le dimanche soutient le besoin de davantage de disponibilite.'),
    q('Logique', 'Tous les candidats admis ont valide leur dossier. Lina n’a pas valide son dossier. Que peut-on conclure ?', ['Lina sera certainement refusee.', 'Lina ne sera pas admise tant que son dossier n’est pas valide.', 'Lina a deja ete admise.', 'Tous les candidats ont le dossier de Lina.', 'Lina a valide son dossier.'], 1, 'La validation est une condition necessaire de l’admission ; sans elle, l’admission ne peut avoir lieu.'),
    q('Causalite', 'Depuis que le parking est devenu payant, le nombre de voitures stationnees a diminue. Quelle information empecherait le plus de conclure que le prix est la cause de la baisse ?', ['Le prix est faible.', 'Le parking est proche du centre-ville.', 'Une ligne de tramway a ouvert le meme mois.', 'Le parking est surveille.', 'Les tickets sont dematerialises.'], 2, 'Le nouveau tramway est une explication concurrente, qui fragilise l’attribution causale.'),
    q('Contradiction', 'Quel enonce contredit : « Aucune des propositions du dossier n’est definitivement ecartee » ?', ['Certaines propositions sont en cours d’etude.', 'Toutes les propositions restent possibles.', 'Une proposition ne pourra plus etre examinee.', 'Le dossier sera discute demain.', 'Les avis restent partages.'], 2, 'Dire qu’une proposition ne sera plus examinee revient a l’ecarter definitivement.'),
    q('Conclusion', '« Cette formation est exigeante : les devoirs sont frequents et les retours individualises. » Quelle conclusion est la mieux fondee ?', ['La formation est forcement mauvaise.', 'Les etudiants n’ont aucun temps libre.', 'La formation demande un investissement regulier.', 'Tous les retours sont positifs.', 'Les devoirs sont impossibles a terminer.'], 2, 'Les elements cites etablissent une exigence et un travail suivi, pas les autres affirmations.') ] },
  { id: 'conditions', index: '04', title: 'Conditions minimales', description: 'Decider quelle information suffit a repondre.', icon: 'list-checks', questions: [
    q('Donnees suffisantes', 'Quel est le prix d’un article apres remise ? (1) Son prix initial est 60 euros. (2) La remise est de 20 %.', ['(1) suffit seule', '(2) suffit seule', '(1) et (2) ensemble suffisent', 'Chaque information seule suffit', 'Les informations ne suffisent pas'], 2, 'Il faut connaitre le prix initial et le taux de remise. Ensemble, 60 x 0,8 = 48.'),
    q('Donnees suffisantes', 'Le triangle ABC est-il rectangle ? (1) Ses cotes mesurent 3, 4 et 5. (2) Son angle le plus grand mesure 90 degres.', ['(1) suffit seule', '(2) suffit seule', '(1) et (2) ensemble suffisent', 'Chaque information seule suffit', 'Les informations ne suffisent pas'], 3, 'Le triplet 3-4-5 implique un triangle rectangle ; un angle de 90 degres aussi.'),
    q('Donnees suffisantes', 'Quelle est la valeur de y ? (1) x + y = 12. (2) x = 5.', ['(1) suffit seule', '(2) suffit seule', '(1) et (2) ensemble suffisent', 'Chaque information seule suffit', 'Les informations ne suffisent pas'], 2, 'L’equation donne une relation ; avec x = 5, y = 7.'),
    q('Donnees suffisantes', 'Le nombre entier n est-il pair ? (1) n est divisible par 4. (2) n est un multiple de 6.', ['(1) suffit seule', '(2) suffit seule', '(1) et (2) ensemble suffisent', 'Chaque information seule suffit', 'Les informations ne suffisent pas'], 3, 'Un nombre divisible par 4 est pair, et un multiple de 6 est aussi pair.'),
    q('Donnees suffisantes', 'Paul est-il plus age que Sarah ? (1) Paul a 26 ans. (2) Sarah est nee avant 1999.', ['(1) suffit seule', '(2) suffit seule', '(1) et (2) ensemble suffisent', 'Chaque information seule suffit', 'Les informations ne suffisent pas'], 4, 'La date actuelle et l’age precis de Sarah manquent ; on ne peut pas trancher avec certitude.') ] },
  { id: 'expression', index: '05', title: 'Expression', description: 'Choisir la formulation la plus juste et la plus claire.', icon: 'pen-line', questions: [
    q('Vocabulaire', 'Complete : « Cette mesure vise a ______ les inegalites d’acces au soin. »', ['accentuer', 'resorber', 'deplacer', 'observer', 'inventer'], 1, '« Resorber » signifie reduire progressivement, faire disparaitre.'),
    q('Syntaxe', 'Quelle phrase est correctement ecrite ?', ['Les donnees que nous avons analysees confirme notre hypothese.', 'Les donnees que nous avons analyse confirme notre hypothese.', 'Les donnees que nous avons analysees confirment notre hypothese.', 'Les donnees que nous avons analyses confirment notre hypothese.', 'Les donnees que nous avons analyser confirment notre hypothese.'], 2, 'COD « donnees » place avant : analysees ; sujet pluriel : confirment.'),
    q('Connecteur', '« Le cout initial est eleve. ______, les economies realisees sur cinq ans compensent cet investissement. »', ['Pourtant', 'Ainsi', 'Par exemple', 'En revanche', 'D’ailleurs'], 0, '« Pourtant » introduit ici l’opposition entre cout initial et economies futures.'),
    q('Precision', 'Quelle formulation est la plus precise ?', ['Le projet est bien.', 'Le projet semble assez interessant en general.', 'Le projet devrait sans doute marcher un peu.', 'Le projet reduit de 18 % le temps de traitement moyen.', 'Le projet est clairement superieur.'], 3, 'Elle apporte un indicateur mesurable, contrairement aux jugements vagues.'),
    q('Coherence', 'Choisis la suite la plus coherente : « Les resultats sont encourageants, ______ ils doivent etre interpretes avec prudence en raison de la taille reduite de l’echantillon. »', ['donc', 'mais', 'car', 'puisque', 'ainsi'], 1, '« Mais » marque la restriction annoncee dans la seconde proposition.') ] },
  { id: 'logique', index: '06', title: 'Logique', description: 'Trouver la structure derriere une suite ou une contrainte.', icon: 'brain-circuit', questions: [
    q('Suite', 'Complete la suite : 3, 7, 15, 31, ...', ['47', '55', '61', '63', '65'], 3, 'Chaque terme est le precedent multiplie par 2, puis +1 : 31 x 2 + 1 = 63.'),
    q('Classement', 'Cinq dossiers A, B, C, D et E sont classes. A est avant B. C est apres D. E est avant A. Quelle proposition est necessairement vraie ?', ['B est premier', 'E est avant B', 'C est dernier', 'D est premier', 'A est avant E'], 1, 'E est avant A, lui-meme avant B : E est donc necessairement avant B.'),
    q('Code', 'Si dans un code, chaque lettre avance de deux rangs dans l’alphabet, comment code-t-on MATH ?', ['OCVJ', 'OCVJ', 'NBUI', 'OCVG', 'QCVJ'], 0, 'M->O, A->C, T->V, H->J : OCVJ.'),
    q('Ensemble', 'Tous les cercles bleus sont petits. Certains objets petits sont lourds. Quelle affirmation est necessairement vraie ?', ['Tous les objets lourds sont bleus.', 'Certains cercles bleus sont lourds.', 'Aucun cercle bleu n’est lourd.', 'Les cercles bleus sont petits.', 'Tous les petits objets sont bleus.'], 3, 'Seule la premiere relation est affirmee avec certitude.'),
    q('Suite', 'Complete : 2, 6, 12, 20, 30, ...', ['36', '40', '42', '44', '48'], 2, 'Les ecarts sont +4, +6, +8, +10, puis +12 : 42.') ] }
];
function q(tag, text, answers, correct, explanation) { return { tag, text, answers, correct, explanation }; }
const state = { module: null, index: 0, selected: null, answers: [], startedAt: 0, elapsed: 0, timer: null, mix: false, fullExam: false, examNumber: null };
const storeKey = 'atlas-tage-mage-progress-v1';
const saved = JSON.parse(localStorage.getItem(storeKey) || '{"answered":0,"correct":0,"minutes":0,"dates":[]}');
const $ = (selector) => document.querySelector(selector);
function iconRefresh(){ lucide.createIcons(); }
function save(){ localStorage.setItem(storeKey, JSON.stringify(saved)); }
function formatTime(seconds){ const m = Math.floor(seconds / 60).toString().padStart(2,'0'); const s = (seconds % 60).toString().padStart(2,'0'); return `${m}:${s}`; }
function refreshStats(){ $('#stat-answered').textContent = saved.answered; $('#stat-accuracy').textContent = saved.answered ? `${Math.round(saved.correct / saved.answered * 100)} %` : '--'; $('#stat-time').textContent = `${saved.minutes} min`; const uniqueDates = [...new Set(saved.dates)]; let streak = 0, cursor = new Date(); while(uniqueDates.includes(cursor.toISOString().slice(0,10))){ streak++; cursor.setDate(cursor.getDate()-1); } $('#stat-streak').textContent = `${streak} jour${streak === 1 ? '' : 's'}`; }
function renderModules(){ $('#module-grid').innerHTML = modules.map(m => `<article class="module"><div class="module-top"><span class="module-index">${m.index} / 06</span><span class="module-icon"><i data-lucide="${m.icon}"></i></span></div><h3>${m.title}</h3><p>${m.description}</p><div class="module-footer"><span>5 questions · 20 min</span><button class="start-module" data-module="${m.id}" aria-label="Commencer ${m.title}"><i data-lucide="arrow-up-right"></i></button></div></article>`).join(''); iconRefresh(); document.querySelectorAll('[data-module]').forEach(btn => btn.addEventListener('click', () => { state.fullExam=false; state.examNumber=null; startQuiz(modules.find(m => m.id === btn.dataset.module)); })); }
function renderExams(){ $('#exam-grid').innerHTML = window.mockExamLabels.map((label,index)=>`<article class="exam-card"><span class="exam-number">EXAMEN 0${index + 1}</span><h3>${label}</h3><p>6 sous-tests · 15 questions chacun · ordre renouvele a chaque lancement.</p><div class="exam-card-footer"><span>90 Q · 120 MIN</span><button class="start-module" data-exam="${index + 1}" aria-label="Commencer ${label}"><i data-lucide="play"></i></button></div></article>`).join(''); iconRefresh(); document.querySelectorAll('[data-exam]').forEach(btn=>btn.addEventListener('click',()=>startMockExam(Number(btn.dataset.exam)))); }
function getQuestions(){ return state.module.questions; }
function startMockExam(number){ state.examNumber=number; state.fullExam=true; startQuiz(window.createMockExam(number)); }
function startQuiz(module, mix = false){ state.module = mix ? { title: 'Mix express', id: 'mix', questions: [...modules.flatMap(m => m.questions.slice(0,1))].sort(()=>Math.random()-.5) } : module; state.index=0; state.selected=null; state.answers=Array(getQuestions().length).fill(null); state.startedAt=Date.now(); state.elapsed=0; state.mix=mix; const duration=state.fullExam?7200:(mix?900:1200); $('#quiz-mode').textContent = state.fullExam ? 'EXAMEN BLANC' : (mix ? 'MIX EXPRESS' : 'ENTRAINEMENT CIBLE'); $('#quiz-category').textContent = state.module.title.toUpperCase(); $('#question-total').textContent = String(getQuestions().length).padStart(2,'0'); $('#quiz-modal').showModal(); clearInterval(state.timer); state.timer=setInterval(() => { state.elapsed=Math.floor((Date.now()-state.startedAt)/1000); $('#timer-value').textContent=formatTime(Math.max(0,duration-state.elapsed)); },1000); renderQuestion(); }
function renderQuestion(){ const question=getQuestions()[state.index]; const answer=state.answers[state.index]; $('#question-number').textContent=String(state.index+1).padStart(2,'0'); $('#question-tag').textContent=question.tag.toUpperCase(); const context=$('#question-context'); context.hidden=!question.context; context.textContent=question.context || ''; $('#question-text').textContent=question.text; $('#answers').innerHTML=question.answers.map((a,i)=>`<button class="answer ${answer?.selected === i?'selected':''} ${answer?.submitted && i === question.correct ? 'correct':''} ${answer?.submitted && i === answer.selected && i !== question.correct ? 'wrong':''}" data-answer="${i}" ${answer?.submitted?'disabled':''}><span class="answer-letter">${String.fromCharCode(65+i)}</span><span>${a}</span></button>`).join(''); $('#feedback').hidden=!answer?.submitted; $('#feedback').textContent=answer?.submitted ? question.explanation : ''; $('#question-hint').textContent=answer?.submitted ? (answer.selected===question.correct ? 'Bonne reponse.' : 'A retenir pour la prochaine fois.') : 'Choisis une reponse.'; $('#next-question').innerHTML=answer?.submitted ? (state.index===getQuestions().length-1?'Voir mon bilan <i data-lucide="bar-chart-3"></i>':'Question suivante <i data-lucide="arrow-right"></i>') : 'Valider <i data-lucide="arrow-right"></i>'; const dots=$('#question-dots'); dots.className=`question-dots ${state.fullExam?'full-dots':''}`; dots.innerHTML=getQuestions().map((_,i)=>`<button class="question-dot ${i===state.index?'active':''} ${state.answers[i]?.submitted?'answered':''}" data-dot="${i}">${i+1}</button>`).join(''); $('#live-score').textContent=state.answers.reduce((sum,a,i)=>sum+(a?.submitted?(a.selected===getQuestions()[i].correct?4:-1):0),0); document.querySelectorAll('[data-answer]').forEach(btn=>btn.addEventListener('click',()=>{state.answers[state.index]={selected:Number(btn.dataset.answer),submitted:false};renderQuestion();})); document.querySelectorAll('[data-dot]').forEach(btn=>btn.addEventListener('click',()=>{state.index=Number(btn.dataset.dot);renderQuestion();})); iconRefresh(); }
function submitOrNext(){ const answer=state.answers[state.index]; if(!answer){ $('#question-hint').textContent='Selectionne une reponse avant de valider.'; return; } if(!answer.submitted){ answer.submitted=true; renderQuestion(); return; } if(state.index===getQuestions().length-1){ finishQuiz(); } else { state.index++; renderQuestion(); } }
function finishQuiz(){ clearInterval(state.timer); $('#quiz-modal').close(); const questions=getQuestions(); const submitted=state.answers.filter(Boolean); const correct=state.answers.reduce((total,a,i)=>total+(a?.submitted && a.selected===questions[i].correct ? 1 : 0),0); const wrong=state.answers.reduce((total,a,i)=>total+(a?.submitted && a.selected!==questions[i].correct ? 1 : 0),0); const blank=questions.length-submitted.length; const score=correct*4-wrong; const minutes=Math.max(1,Math.round(state.elapsed/60)); saved.answered+=submitted.length; saved.correct+=correct; saved.minutes+=minutes; const today=new Date().toISOString().slice(0,10); saved.dates.push(today); save(); refreshStats(); $('#result-title').textContent=score >= 12 ? 'Bonne cadence.' : score >= 4 ? 'Tu construis tes reperes.' : 'Chaque erreur est une information.'; $('#result-score').textContent=score; $('#result-summary').textContent=`${correct} bonne${correct>1?'s':''} reponse${correct>1?'s':''} sur ${questions.length}. Cette serie a dure ${formatTime(state.elapsed)}.`; $('#result-breakdown').innerHTML=`<div><b>${correct}</b><small>justes</small></div><div><b>${wrong}</b><small>fausses</small></div><div><b>${blank}</b><small>passees</small></div>`; $('#results-modal').showModal(); iconRefresh(); }
$('#next-question').addEventListener('click',submitOrNext); $('#leave-quiz').addEventListener('click',()=>{clearInterval(state.timer);$('#quiz-modal').close();state.fullExam=false;}); $('#start-mix').addEventListener('click',()=>{state.fullExam=false;startQuiz(null,true);}); $('#close-results').addEventListener('click',()=>$('#results-modal').close()); $('#return-dashboard').addEventListener('click',()=>$('#results-modal').close()); $('#retry-quiz').addEventListener('click',()=>{const previous=state.module;$('#results-modal').close();if(state.examNumber && previous.fullExam){startMockExam(state.examNumber);}else{state.fullExam=false;startQuiz(previous,state.mix);}}); $('#open-tips').addEventListener('click',()=>$('#tips-modal').showModal()); $('#close-tips').addEventListener('click',()=>$('#tips-modal').close()); $('#reset-progress').addEventListener('click',()=>{if(confirm('Reinitialiser toute ta progression locale ?')){Object.assign(saved,{answered:0,correct:0,minutes:0,dates:[]});save();refreshStats();}}); $('#pdf-input').addEventListener('change',(event)=>{const file=event.target.files[0];if(!file)return;const link=$('#pdf-link');link.href=URL.createObjectURL(file);link.hidden=false;link.style.display='inline-flex';link.querySelector ? null : null;});
renderModules();renderExams();refreshStats();iconRefresh();
